site_information:
  title: Opal Nova
  description: "Some web page description"
  logo: http://some_path.png

navigation_items:
  - label: Blog
    children: # No URL specified here since it's just a branch node without a page associated with it
      - label: Posts
        url: /blog.html
      - label: Tags
        url: /tags.html
  - label: About
    url: /about.html
